from django.db import models


class Group(models.Model):
    name = ...
    priority = ...
    workers = ...


class Worker(models.Model):
    name = ...
    last_name = ...
    surname = ...
    self_priority = ...
    groups = ...


class WorkerGroup(models.Model):
    group = ...
    worker = ...
